### ISSUE TITLE
problem installing Radionet on Mopidy on raspberry pi 4

### ISSUE THREAD

**Issue by hikerlt1951** [plintx/mopidy-radionet#4]
On raspberry pi 4 , raspbian OS, using IRIS

Trying to install and run RadioNet

install it by :
sudo pip3 install Mopidy-RadioNet
sudo systemctl restart Mopidy

When I do

sudo service mopidy status, see the following :

pi@raspberrypi:~ $ sudo service mopidy status
● mopidy.service - Mopidy music server
Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
Active: active (running) since Mon 2020-09-14 13:59:29 EDT; 23s ago
Process: 3003 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
Process: 3004 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
Main PID: 3005 (mopidy)
Tasks: 15 (limit: 4915)
CGroup: /system.slice/mopidy.service
└─3005 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Sep 14 13:59:30 raspberrypi mopidy[3005]: self.radionet.set_lang(str(config[‘radionet’][‘language’]))
Sep 14 13:59:30 raspberrypi mopidy[3005]: File “/usr/local/lib/python3.7/dist-packages/mopidy_radionet/radionet.py”, l
Sep 14 13:59:30 raspberrypi mopidy[3005]: logging.error("Radio.net not supported language: " - str(lang))
Sep 14 13:59:30 raspberrypi mopidy[3005]: TypeError: unsupported operand type(s) for -: ‘str’ and 'str’
Sep 14 13:59:30 raspberrypi mopidy[3005]: INFO [Audio-2] mopidy.audio.actor Audio output set to “alsasink”
Sep 14 13:59:30 raspberrypi mopidy[3005]: INFO [MainThread] mopidy.commands Starting Mopidy core
Sep 14 13:59:30 raspberrypi mopidy[3005]: INFO [MainThread] mopidy.commands Starting Mopidy frontends: IrisFrontend,
Sep 14 13:59:30 raspberrypi mopidy[3005]: INFO [IrisFrontend-9] mopidy_iris.core Starting Iris 3.52.4
Sep 14 13:59:30 raspberrypi mopidy[3005]: INFO [HttpFrontend-11] mopidy.http.actor HTTP server running at [::ffff:0.
Sep 14 13:59:30 raspberrypi mopidy[3005]: INFO [MainThread] mopidy.commands Starting GLib mainloop
pi@raspberrypi:~ $

**Comment by hikerlt1951** [comment]
Some more updated info attached below, hope this helps .  
**********************
pi@raspberrypi:~ $ sudo systemctl enable mopidy
Synchronizing state of mopidy.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mopidy
pi@raspberrypi:~ $ mopidy
INFO     Starting Mopidy 2.3.1
INFO     Loading config from builtin defaults
INFO     Loading config from /home/pi/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local, radionet
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend, RadioNetBackend
INFO     Audio output set to "autoaudiosink"
INFO     No local library metadata cache found at /home/pi/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
ERROR    Got un-handled exception from RadioNetBackend
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy/commands.py", line 386, in start_backends
    config=config, audio=audio).proxy()
  File "/home/pi/.local/lib/python2.7/site-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy_radionet/backend.py", line 33, in __init__
    self.radionet.set_lang(str(config['radionet']['language']))
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy_radionet/radionet.py", line 67, in set_lang
    logging.error("Radio.net not supported language: " - str(lang))
TypeError: unsupported operand type(s) for -: 'unicode' and 'str'
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
ERROR    Frontend (HttpFrontend) initialization error: HTTP server startup failed: [Errno 98] Address already in use
INFO     Starting GLib mainloop

INFO     Interrupted. Exiting...
INFO     Stopping Mopidy frontends
^CINFO     Stopping Mopidy core
INFO     Stopping Mopidy backends
INFO     Stopping Mopidy audio
INFO     Stopping Mopidy mixer
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ sudo mopidyctl config
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s [%(threadName)s] %(name)s %(message)s
color = false
config_file =

[audio]
mixer = software
mixer_volume = 
output = alsasink
buffer_time = 

[proxy]
scheme = 
hostname = 
port = 
username = 
password = 

[radionet]
enabled = true
username = alice666.9
password = ********
language = net
min_bitrate = 96

[local]
enabled = true
media_dir = /home/pi/Music
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
included_file_extensions = 
excluded_file_extensions = 
  .cue
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
directories = 
  Albums                  local:directory?type=album
  Artists                 local:directory?type=artist
  Composers               local:directory?type=artist&role=composer
  Genres                  local:directory?type=genre
  Performers              local:directory?type=artist&role=performer
  Release Years           local:directory?type=date&format=%25Y
  Tracks                  local:directory?type=track
  Last Week's Updates     local:directory?max-age=604800
  Last Month's Updates    local:directory?max-age=2592000
timeout = 10
use_artist_sortname = false
album_art_files = 
  *.jpg
  *.jpeg
  *.png

[iris]
enabled = true
country = NZ
locale = en_NZ
spotify_authorization_url = https://jamesbarnsley.co.nz/iris/auth_spotify.php
lastfm_authorization_url = https://jamesbarnsley.co.nz/iris/auth_lastfm.php
genius_authorization_url = https://jamesbarnsley.co.nz/iris/auth_genius.php
data_dir = $XDG_DATA_DIR/iris

[internetarchive]
enabled = true
base_url = http://archive.org
collections = 
  audio
  etree
  librivoxaudio
  audio_bookspoetry
  audio_tech
  audio_music
  audio_news
  audio_foreign
  audio_podcast
  audio_religion
audio_formats = 
  VBR MP3
  64Kbps MP3
image_formats = 
  JPEG
  JPEG Thumb
browse_limit = 100
browse_views = 
  downloads desc|Views
  titleSorter asc|Title
  publicdate desc|Date Archived
  date desc|Date Published
  creatorSorter asc|Creator
search_limit = 20
search_order = 
cache_size = 128
cache_ttl = 86400
retries = 3
timeout = 10

[file]
enabled = true
media_dirs = 
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins = 
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000
pi@raspberrypi:~ $
