### ISSUE TITLE
Searching does not work

### ISSUE THREAD

**Issue by kokosowy** [plintx/mopidy-radionet#9]
Hi,

Version v0.2.2, browsing works fine, but when I try to search Iris is getting into infinite loop looking for artist and Mowecl crashes (getting blank page, js errors 'e.uri is undefined' in console).

If I can deliver you any other logs, just tell me how to do this. Journalctl says nothing about this event, maybe I need to raise trace level. Anyway just letting you know.

K

**Comment by daniele-athome** [comment]
Searching doesn't work also from the mpd frontend:

```
feb 14 19:37:39 speaker-bedroom mopidy[2989]: ERROR    [MpdSession-20] pykka Unhandled exception in MpdSession (urn:uuid:2e8198dc-6948-4f5e-b6d6-8fe5a04714f9):
feb 14 19:37:39 speaker-bedroom mopidy[2989]: Traceback (most recent call last):
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self._handle_receive(envelope.message)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 307, in _handle_receive
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return self.on_receive(message)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/network.py", line 443, in on_receive
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     self.on_line_received(line)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/session.py", line 32, in on_line_received
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self.dispatcher.handle_request(line)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 46, in handle_request
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return self._call_next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return self._call_next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 87, in _authenticate_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return self._call_next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 106, in _command_list_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self._call_next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 139, in _idle_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self._call_next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 152, in _add_ok_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self._call_next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return next_filter(request, response, filter_chain)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 164, in _call_handler_filter
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self._format_response(self._call_handler(request))
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 178, in _call_handler
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return protocol.commands.call(tokens, context=self.context)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/protocol/__init__.py", line 212, in call
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return self.handlers[tokens[0]](context, *tokens[1:])
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/protocol/__init__.py", line 170, in validate
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return func(*args, **kwargs)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/protocol/music_db.py", line 443, in search
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     results = context.core.library.search(query).get()
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     _compat.reraise(*self._data['exc_info'])
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     raise value
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self._handle_receive(envelope.message)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return callee(*message.args, **message.kwargs)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 316, in search
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     result = future.get()
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     _compat.reraise(*self._data['exc_info'])
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     raise value
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     response = self._handle_receive(envelope.message)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     return callee(*message.args, **message.kwargs)
feb 14 19:37:39 speaker-bedroom mopidy[2989]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_radionet/library.py", line 91, in search
feb 14 19:37:39 speaker-bedroom mopidy[2989]:     self.backend.radionet.do_search(' '.join(query['any']))
```
